FROM golang:1.17 as deps

EXPOSE 3000
EXPOSE 6060

ENV PROJECT_PATH=/go/src/github.com/marc-campbell/nicedishy
WORKDIR $PROJECT_PATH

## Get deps
ADD go.mod go.sum $PROJECT_PATH
RUN --mount=type=cache,target=/root/.cache go mod download

## Now add the project and compile
COPY . /go/src/github.com/marc-campbell/nicedishy
RUN --mount=type=cache,target=/root/.cache make build

ENTRYPOINT ["./bin/nicedishy-api"]
