apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: ""
  creationTimestamp: null
  labels:
    io.kompose.service: retool
  name: retool
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      io.kompose.service: retool
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: retool
    spec:
      containers:
      - args:
        - bash
        - -c
        - ./docker_scripts/wait-for-it.sh -t 0 $POSTGRES_HOST:$POSTGRES_PORT;
          ./docker_scripts/start_api.sh
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: retoolsecrets
              key: jwt_secret
        - name: SERVICE_TYPE
          value: MAIN_BACKEND,DB_CONNECTOR,DB_SSH_CONNECTOR
        - name: NODE_ENV
          value: production
        - name: POSTGRES_DB
          value: hammerhead_production
        - name: POSTGRES_HOST
          value: retool-postgres
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: retool_internal_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: retoolsecrets
              key: postgres_password
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: retoolsecrets
              key: encryption_key
        - name: LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: retoolsecrets
              key: license_key
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: retoolsecrets
              key: google_client_id
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: retoolsecrets
              key: google_client_secret
        image: tryretool/backend:2.68.20
        name: retool
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: 2048M
          requests:
            cpu: "1"
            memory: 1024M
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: ""
    dev.okteto.com/auto-ingress: "true"
  creationTimestamp: null
  labels:
    io.kompose.service: retool
  name: retool
spec:
  type: ClusterIP
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    io.kompose.service: retool
status:
  loadBalancer: {}
