FROM golang:1.16 as deps

RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - \
  && echo "deb http://apt.postgresql.org/pub/repos/apt/ buster-pgdg main" > /etc/apt/sources.list.d/PostgreSQL.list \
  && apt-get update && apt-get install -y --no-install-recommends \
    postgresql-client-10 \
  && rm -rf /var/lib/apt/lists/*


ADD ./bin/nicedishy-api /nicedishy-api
ADD ./bin/grafana-proxy /grafana-proxy

ENTRYPOINT ["/nicedishy-api"]
